categories:
- Variant Analysis
description: 'SomaticSniper:identify single nucleotide positions that are different between tumor and normal'
homepage_url: https://github.com/genome/somatic-sniper
long_description: |
The purpose of this program is to identify single nucleotide positions that are different between tumor and normal (or in theory, any two bam files). It takes a tumor bam and a normal bam and compares the two to determine the differences.
name: somaticsniper
owner: elixir-it
remote_repository_url: https://github.com/Laniakea-elixir-it/GDC-DNA-Seq-pipeline-galaxy-wrapper/tree/master/somatic-sniper-wrapper
type: unrestricted
